insert into TO_DO(ID,USERNAME,DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10001,'Mangesh','Get AWS Certified',CURRENT_DATE(), false);

insert into TO_DO(ID,USERNAME,DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10002,'Mangesh','Get JAVA Certified',CURRENT_DATE(), false);

insert into TO_DO(ID,USERNAME,DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10003,'Mangesh','Get SPRING Certified',CURRENT_DATE(), false);

insert into TO_DO(ID,USERNAME,DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10004,'Mangesh','Get HIBERNATE Certified',CURRENT_DATE(), false);

insert into TO_DO(ID,USERNAME,DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10005,'Mangesh','Get React Certified',CURRENT_DATE(), false);